### ISSUE TITLE
Sidebar.html menu selection

### ISSUE THREAD

**Issue by emzzme** [app-generator/flask-datta-able-pro#2]
hi, i want to ask somethink. I am using flask dattaable pro dashboard but my sidebar does not activate the menu item. What ever you chose, it doesnt matter, menu do not show which page you are in. I think its about the sidebar.html nav menu item but i cannot find.  Also this problem seen in your demo page.

I found the problem. Its about app/base/templates/includes/sidebar.html ---> in menu part,  {% if 'index' in segment %} active {% endif %} {% if 'alternative' in segment %} active {% endif %}" section is missing

**Comment by app-generator** [comment]
Hello @emzzme, 

The context of this problem is the following: the current page is known by the backend via `segment` variable but the parent menu information is lost. 
A possible fix is to use `local storage` to expand the proper parent menu based on the current page.

Anyway, we will investigate this issue and publish the fix once is tested.

**Comment by emzzme** [comment]
Thanks, I am waiting this fix. Have a nice work

**Comment by emzzme** [comment]
I have a solution,

for example, this is in nav-bar menu, and if I add bold part in <li> part then it will work
<li data-username="informations" class="nav-item **{% if 'informations' in segment %} active {% endif %}**">
                        <a class="nav-link" href="/informations.html">
                            <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                            <span class="pcoded-mtext">Informations</span>                            
                        </a>
                    </li>
