### ISSUE TITLE
Error 404 for extra helper 

### ISSUE THREAD

**Issue by pawelfilo** [app-generator/flask-datta-able-pro#3]
For every extra helper (widgets, tables etc.) I get error 404:

![image](https://user-images.githubusercontent.com/6053226/189688520-03cff8aa-ebcd-4f3d-915f-4706034f853c.png)
![image](https://user-images.githubusercontent.com/6053226/189688752-b3a8bac1-1823-4b7f-93bc-32e77b43389e.png)

**Comment by app-generator** [comment]
Hello @pawelfilo 

The link is not linked to a backend action and is just a link sample provided by the design. 

Please update the line as shown below (page `widgets-table.html`)

```html
<p>Use our extra helper file for quick widgets setup in your page - <a href="#page-table" class="alert-link">CHECKOUT</a></p>
```

**Comment by pawelfilo** [comment]
As I can see it is connected, but we are missing this file:
![image](https://user-images.githubusercontent.com/6053226/189746468-1e71179e-3bd4-4ea1-936e-1a2f76e15838.png)

**Comment by app-generator** [comment]
Hello @pawelfilo 

There is no missing file in the kit. 
Please note that the project comes with 50+ pages enhanced with a super rich UI kit. 

At some point, the pages might have a few broken links but this can happen due to the complexity of the product. 

Let us know if you need further assistance. 

AppSeed Support
